### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ssoyeong-lee** [ft-transcendence-seoul/frontend#44]
# 페이지별 정리
## /main
- [x] 2 factor api 부착
- [x] status card api 부착
- [x] history card api 부착
## /play
- [x] match 버튼 클릭 시 api 부착
- [x] cancle 버튼 클릭 시 api 부착
- [x] 매칭 소켓 받기 -> 게임화면으로 라우팅
## /chat
- [x] dm 채팅
- [x] 채널 채팅
- [x] private 채널에서 채널 초대 버튼 생성
- [x] 채널 초대 버튼 클릭 시 유저 검색 모달 생성 -> SearchCard 재사용
- [ ] 유저 컨트롤에서 이미 어드민인 사람 클릭 시 어드민 회수 버튼으로 변경
- [x] 유저 컨트롤에서 프로필 보기 클릭 시 해당 유저 페이지로 라우팅
- [ ] 뮤트 api 부착
- [x] 플레이 게임 api 부착
## /game
- [x] 게임 소켓 연결
- [x] 애니메이션 렌더링(requestanimationFrame 사용)
- [x] 게임 보드 16:9 비율 -> 2:1 비율로 변경
- [x] 결과 화면 모달
## Notification Center
- [ ] 알림 리스트(?)에 수락, 거절 버튼 추가
- [ ] 수락, 거절 버튼에 api 부착
- [x] 알림 없을 때, 없다고 보여줄 것.
## 공통
- [x] api 부착단에서 200이 아니라면 에러 메시지 보여주기
- [x] 로그아웃 상태 시, 로그인 페이지로 이동
- [x] input 태그에서 입력 데이터 유효성 검사 -> 에러 띄우기
- [x] 백엔드에서 변경된 인터페이스에 맞도록 변경  및 반영
# 정할 것들
- [x] 친선 게임 시 과정?
- [x] 매칭 시 그냥 토스트 메시지로...?
